In [3]:
!git clone https://github.com/gx-interview/AlvaroBlanco.git
%cd AlvaroBlanco

Cloning into 'AlvaroBlanco'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 2 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (4/4), done.
/Users/alvaroporcel/Downloads/AlvaroBlanco

In [4]:
!git checkout -b Alvaro-Porcel-Blanco

Switched to a new branch 'Alvaro-Porcel-Blanco'

In [5]:
import pandas as pd
from datetime import timedelta

df = pd.read_csv('source.csv')

In [6]:
df.head(5)

       Name                 Datetime  Amount  Price  Purity
0  ProductA  2022-01-01T01:00:00.000      10  22.09  Impure
1  ProductA  2022-01-01T02:00:00.000      15  24.22    Pure
2  ProductA  2022-01-01T03:00:00.000      10  25.96  Impure
3  ProductA  2022-01-01T04:00:00.000      20  21.16  Impure
4  ProductA  2022-01-01T05:00:00.000      10  20.05    Pure

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      24 non-null     object
 1   Datetime  24 non-null     object
 2   Amount    24 non-null     int64
 3   Price     24 non-null     float64
 4   Purity    24 non-null     object
dtypes: float64(1), int64(1), object(3)
memory usage: 1.1+ KB

column 'Datetime' UTC to UTC+6

In [8]:
df['Datetime'] = pd.to_datetime(df['Datetime']) + timedelta(hours=6)

In [9]:
df.head(1)

       Name            Datetime  Amount  Price  Purity
0  ProductA 2022-01-01 07:00:00      10  22.09  Impure

Datetime is "Datetime"

In [10]:
if not pd.api.types.is_datetime64_any_dtype(df['Datetime']):
    df['Datetime'] = pd.to_datetime(df['Datetime'])

In [11]:
def calculate_total(row, df):
    purity_factor = 0.75 if row['Purity'] == 'Impure' else 1.0

    if row['Name'] == 'ProductA':
        return row['Amount'] * row['Price'] * purity_factor

    elif row['Name'] == 'ProductB':
        # Search price of ProductA with the same Datetime
        matching_a = df[(df['Name'] == 'ProductA') & (df['Datetime'] == row['Datetime'])]
        if not matching_a.empty:
            price_a = matching_a.iloc[0]['Price']
            diff_price = row['Price'] - price_a
            return row['Amount'] * diff_price * purity_factor
        else:
            return 0
    else:
        return 0

In [12]:
df['total'] = df.apply(lambda row: calculate_total(row, df), axis=1)

In [13]:
df.to_csv('result.csv', index=False)

In [15]:
ls

README.md   result.csv  source.csv